query getEdgesInTimeRange {
  Edges(limit: 50) {
    startNode {
      id
      name
      latitude
      longitude
    }
    stopNode {
      id
      name
      latitude
      longitude
    }
  }
}
