import { STORE } from '@constants';

const {
  MAP_STYLE,
  GRAPH_TYPE,
  LIMIT,
  NETWORK_OPTIONS,
  IS_EDGES_VISIBLE,
  IS_PATH_CALCULATION,
  PATH_LENGTH,
} = STORE;

const LOCAL_STORAGE_KEYS = {
  MAP_STYLE,
  GRAPH_TYPE,
  LIMIT,
  NETWORK_OPTIONS,
  IS_EDGES_VISIBLE,
  IS_PATH_CALCULATION,
  PATH_LENGTH,
};

export default LOCAL_STORAGE_KEYS;
