const storeConstants = {
  MENU: 'MENU',
  GRAPH_TYPE: 'GRAPH_TYPE',
  TIME_RANGE: 'TIME_RANGE',
  MAP_STYLE: 'MAP_STYLE',
  LIMIT: 'LIMIT',
  SELECTED_NODES: 'SELECTED_NODES',
  IS_HIERARCHICAL_VIEW: 'IS_HIERARCHICAL_VIEW',
  IS_EDGES_VISIBLE: 'IS_EDGES_VISIBLE',
  IS_PATH_CALCULATION: 'IS_PATH_CALCULATION',
  PATH_LENGTH: 'PATH_LENGTH',
  CONTROLLER: 'CONTROLLER',
};

export default storeConstants;
