const storeConstants = {
  CONTROLLER: 'CONTROLLER',
  EDGES_FILTER: 'EDGES_FILTER',
  GRAPH_TYPE: 'GRAPH_TYPE',
  IS_EDGE_VISIBLE: 'IS_EDGES_VISIBLE',
  IS_HIERARCHICAL_VIEW: 'IS_HIERARCHICAL_VIEW',
  IS_PATH_CALCULATION: 'IS_PATH_CALCULATION',
  IS_TOP_NODES: 'IS_TOP_NODES',
  LIMIT: 'LIMIT',
  MAP_STYLE: 'MAP_STYLE',
  MENU: 'MENU',
  PATH_LENGTH: 'PATH_LENGTH',
  SELECTED_NODES: 'SELECTED_NODES',
  TIME_RANGE: 'TIME_RANGE',
  TOP_NODES: 'TOP_NODES',
};

export default storeConstants;
