const storeConstants = {
  CONTROLLER: 'CONTROLLER',
  EDGES_FILTER: 'EDGES_FILTER',
  GRAPH_TYPE: 'GRAPH_TYPE',
  IS_EDGE_VISIBLE: 'IS_EDGES_VISIBLE',
  IS_HIERARCHICAL_VIEW: 'IS_HIERARCHICAL_VIEW',
  IS_PHYSICS_ENABLED: 'IS_PHYSICS_ENABLED',
  LIMIT: 'LIMIT',
  MAP_STYLE: 'MAP_STYLE',
  MENU: 'MENU',
  MODE: 'MODE',
  PATH_LENGTH: 'PATH_LENGTH',
  PATH_LIMIT: 'PATH_LIMIT',
  SELECTED_NODES: 'SELECTED_NODES',
  TIME_RANGE: 'TIME_RANGE',
};

export default storeConstants;
